version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: url-shortener-postgres
    hostname: postgres
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: wanis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres:
